# Site Settings
title: KOO's blog | Develop blog
email: nevergiveup936@gmail.com
description: Koo's developing diary
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://KOOSANGYOON.github.io" # the base hostname & protocol for your site
google_analytics: "UA-111886516-1"

# User Settings
username: KOO's blog
user_description: 개발자를 향해 노력하는 KOO 입니다!
disqus_username: KOO

# Social Media
# Remove the item if you don't need it
github_username: KOOSANGYOON
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
  - title: TIL
    url: /TIL/
# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
